### PR TITLE
fix neo4j's data type

### PR DESCRIPTION
**Pull request by Nicole00**

### CODE REVIEW

**Comment by ianhhhhhhhhe** [comment]
```
Caused by: java.lang.RuntimeException: Error while encoding: java.lang.RuntimeException: java.lang.Long is not a valid external type for schema of string
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 5, isDeleted), StringType), true, false) AS status#22
```

status is int64.

**Comment by Nicole00** [comment]
> status is int64.

Your  issue is very helpful. Neo4j's data need to make conversion， keep the data type and schema the seem.

**Comment by ianhhhhhhhhe** [comment]
toString will change string `"xxxxx"` into `"\"xxxxx"\"` which changes the value.

**Comment by Nicole00** [comment]
> toString will change string `"xxxxx"` into `"\"xxxxx"\"` which changes the value.
If you want neo4j's data to be corresponding to Nebula's String type property, then when generating ngql, the value will be `\"xxx\"`, which is correct.
if you want neo4j's data to be corresponding to Nebula's Int type property, then when generating ngql, the value will still be xxx.

**Comment by ianhhhhhhhhe** [comment]
No, it's not. For example, I got `{"tom":person{name:"Tom"}}`. And I use this methon, the vertex will be `{ ""tom"":person{name:""Tome""}}. And I cannot use `MATCH (p) WHERE id(p)=="tom" return p`, instead I have to use `MATCH (p) where id(p)=="\"tom\"" return p` to get what I wanted.

So I am afraid that you may need to check the type of the value and do thing:

```
if (record.get(i).`type`().name == "STRING")
  row.update(i, Executor.convert(record.get(i).asString))
else
  row.update(i, Executor.convert(record.get(i).toString))
```

**Comment by Nicole00** [comment]
> ```
> if (record.get(i).`type`().name == "STRING")
>   row.update(i, Executor.convert(record.get(i).asString))
> else
>   row.update(i, Executor.convert(record.get(i).toString))
> ```
for object type, toString will change the data's original value. Maybe neo4j's data type needs a util to process, we should catch all its data type.

**Review by darionyaphet — APPROVED** [review]

**Pull request merged**
